baseURL = "https://countingbeans.co.za/"
theme = "hugo-bearblog"
title = "Counting Beans"
author = "Terrance Brown"
copyright = "Copyright © 2026, Terrance Brown."
locale = "en-GB"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"

[params]
  description = "Notes from a small life."
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Counting Beans"
  enablePostNavigator = true
  dateFormat = "Jan 2006"

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true